version: "3.0"

services:
  base:
    image: hpcutil-base:$HPCUTIL_VERSION
    build:
      context: ./base

  mysql:
    image: mariadb:$MARIADB_VERSION
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - compute
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./slurm/slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - var_lib_mysql:/var/lib/mysql
    expose:
      - "3306"

  slurmdbd:
    image: hpcutil-slurm:$HPCUTIL_VERSION
    build:
      context: ./slurm
      args:
        SLURM_VERSION: $SLURM_VERSION
        HPCUTIL_VERSION: $HPCUTIL_VERSION
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
    expose:
      - "22"
      - "6819"
    depends_on:
      - base
      - mysql

  slurmctld:
    image: hpcutil-slurm:$HPCUTIL_VERSION
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    expose:
      - "22"
      - "6817"
    depends_on:
      - slurmdbd

  c1:
    image: hpcutil-slurm:$HPCUTIL_VERSION
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    expose:
      - "22"
      - "6818"
    depends_on:
      - slurmctld

  c2:
    image: hpcutil-slurm:$HPCUTIL_VERSION
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    expose:
      - "22"
      - "6818"
    depends_on:
      - slurmctld

  frontend:
    image: hpcutil-slurm:$HPCUTIL_VERSION
    command: ["frontend"]
    hostname: frontend
    container_name: frontend
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    ports:
      - "127.0.0.1:6222:22"
    depends_on:
      - slurmctld

  coldfront:
    image: hpcutil-coldfront:$HPCUTIL_VERSION
    build:
      context: ./coldfront
      args:
        HPCUTIL_VERSION: $HPCUTIL_VERSION
    hostname: coldfront
    container_name: coldfront
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
      - srv_www:/srv/www
    expose:
      - "22"
    ports:
      - "127.0.0.1:2443:443"
    depends_on:
      - mysql
      - frontend

  ondemand:
    image: hpcutil-ondemand:$HPCUTIL_VERSION
    build:
      context: ./ondemand
      args:
        HPCUTIL_VERSION: $HPCUTIL_VERSION
    hostname: ondemand
    container_name: ondemand
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    expose:
      - "22"
    ports:
      - "127.0.0.1:3443:443"
    depends_on:
      - frontend

  xdmod:
    image: hpcutil-xdmod:$HPCUTIL_VERSION
    build:
      context: ./xdmod
      args:
        HPCUTIL_VERSION: $HPCUTIL_VERSION
    hostname: xdmod
    container_name: xdmod
    networks:
      - compute
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - home:/home
    expose:
      - "22"
    ports:
      - "127.0.0.1:4443:443"
    depends_on:
      - mysql
      - frontend

volumes:
  etc_munge:
  etc_slurm:
  home:
  var_lib_mysql:
  srv_www:

networks:
  compute:
